 
- name: Deploy Web Application
  hosts: test   #   db, mtn, qa  
  become: yes     #   becoming admin and performing admin tasks
  tasks:
    - name: Install Nginx
      apt:    #  package module      [ sudo apt install ]
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'

    - name: Copy website files
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0755'

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
